identity:
  name: deployment_status_created
  author: langgenius
  label:
    en_US: Deployment Status Created
    zh_Hans: 部署状态创建
    pt_BR: Status de Deployment Criado

description:
  human:
    en_US: Triggers when a deployment status is created
    zh_Hans: 当a deployment status  created时触发
    pt_BR: Dispara quando a deployment status  created
  llm:
    en_US: This trigger activates when a deployment status is created, providing relevant event information.
    zh_Hans: 当a deployment status  created时，此触发器会被激活，提供相关事件信息。
    pt_BR: Este gatilho é ativado when a deployment status is created, fornecendo informações relevantes do evento.

parameters: []

output_schema:
  type: object
  properties:
    repository:
      type: object
      properties:
        name:
          type: string
          description: The repository name
        full_name:
          type: string
          description: The full repository name (owner/repo)
        html_url:
          type: string
          description: The repository URL
        description:
          type: string
          description: The repository description
        private:
          type: boolean
          description: Whether the repository is private
        owner:
          type: object
          properties:
            login:
              type: string
              description: Repository owner username
            avatar_url:
              type: string
              description: Repository owner avatar URL
            html_url:
              type: string
              description: Repository owner profile URL
    sender:
      type: object
      properties:
        login:
          type: string
          description: The username who triggered the event
        avatar_url:
          type: string
          description: The avatar URL of the sender
        html_url:
          type: string
          description: The profile URL of the sender
        type:
          type: string
          description: The type of the sender (User, Bot, etc.)

extra:
  python:
    source: triggers/deployment_status_created.py