identity:
  name: deployment_status_created
  author: langgenius
  label:
    en_US: Deployment Status Created
    zh_Hans: 部署状态创建
    pt_BR: Status de Deployment Criado

description:
  human:
    en_US: Triggers when a deployment status is created
    zh_Hans: 当部署状态创建时触发
    pt_BR: Dispara quando um status de deployment é criado
  llm:
    en_US: This trigger activates when a deployment status is created on a GitHub repository, providing detailed information about the deployment status, deployment, and repository.
    zh_Hans: 当在 GitHub 仓库中创建部署状态时，此触发器会被激活，提供有关部署状态、部署和仓库的详细信息。
    pt_BR: Este gatilho é ativado quando um status de deployment é criado em um repositório do GitHub, fornecendo informações detalhadas sobre o status do deployment, deployment e repositório.

parameters:
  - name: environments
    label:
      en_US: Environment Filter
      zh_Hans: 环境过滤
      pt_BR: Filtro de Ambiente
    type: string
    required: false
    placeholder:
      en_US: "e.g., production, staging, dev-* (comma-separated, supports wildcards)"
      zh_Hans: "例如：production, staging, dev-*（逗号分隔，支持通配符）"
      pt_BR: "ex: production, staging, dev-* (separados por vírgula, suporta wildcards)"
    help:
      en_US: "Only trigger for deployments to these environments"
      zh_Hans: "仅对部署到这些环境时触发"
      pt_BR: "Disparar apenas para deployments nestes ambientes"

  - name: states
    label:
      en_US: Status States Filter
      zh_Hans: 状态过滤
      pt_BR: Filtro de Estados
    type: string
    required: false
    placeholder:
      en_US: "e.g., success, failure, error, pending (comma-separated)"
      zh_Hans: "例如：success, failure, error, pending（逗号分隔）"
      pt_BR: "ex: success, failure, error, pending (separados por vírgula)"
    help:
      en_US: "Only trigger for specific deployment states"
      zh_Hans: "仅对特定部署状态触发"
      pt_BR: "Disparar apenas para estados de deployment específicos"

  - name: exclude_actors
    label:
      en_US: Exclude Actors
      zh_Hans: 排除执行者
      pt_BR: Excluir Atores
    type: string
    required: false
    placeholder:
      en_US: "e.g., deploy-bot, ci-user (comma-separated)"
      zh_Hans: "例如：deploy-bot, ci-user（逗号分隔）"
      pt_BR: "ex: deploy-bot, ci-user (separados por vírgula)"
    help:
      en_US: "Ignore deployments by these actors"
      zh_Hans: "忽略这些执行者的部署"
      pt_BR: "Ignorar deployments por esses atores"

  - name: target_urls
    label:
      en_US: Target URL Filter
      zh_Hans: 目标 URL 过滤
      pt_BR: Filtro de URL de Destino
    type: string
    required: false
    placeholder:
      en_US: "e.g., https://prod.*, https://app.example.com (comma-separated, supports wildcards)"
      zh_Hans: "例如：https://prod.*, https://app.example.com（逗号分隔，支持通配符）"
      pt_BR: "ex: https://prod.*, https://app.example.com (separados por vírgula, suporta wildcards)"
    help:
      en_US: "Only trigger for deployments with these target URLs"
      zh_Hans: "仅对具有这些目标 URL 的部署触发"
      pt_BR: "Disparar apenas para deployments com essas URLs de destino"

  - name: failure_only
    label:
      en_US: Failures Only
      zh_Hans: 仅失败
      pt_BR: Apenas Falhas
    type: boolean
    required: false
    default: false
    help:
      en_US: "Only trigger for failed deployments"
      zh_Hans: "仅对失败的部署触发"
      pt_BR: "Disparar apenas para deployments que falharam"

  - name: production_only
    label:
      en_US: Production Only
      zh_Hans: 仅生产环境
      pt_BR: Apenas Produção
    type: boolean
    required: false
    default: false
    help:
      en_US: "Only trigger for production deployments"
      zh_Hans: "仅对生产环境部署触发"
      pt_BR: "Disparar apenas para deployments de produção"

output_schema:
  type: object
  properties:
    deployment_status:
      type: object
      properties:
        id:
          type: number
          description: The deployment status ID
        state:
          type: string
          description: The state of the deployment status
        target_url:
          type: string
          description: The target URL to associate with this status
        description:
          type: string
          description: A short description of the status
        environment_url:
          type: string
          description: The URL for accessing the environment
        log_url:
          type: string
          description: The URL to view deployment logs
        created_at:
          type: string
          description: When the deployment status was created
        updated_at:
          type: string
          description: When the deployment status was last updated
        creator:
          type: object
          properties:
            login:
              type: string
              description: The username of the status creator
            avatar_url:
              type: string
              description: The avatar URL of the status creator
            html_url:
              type: string
              description: The profile URL of the status creator
            type:
              type: string
              description: The type of the status creator (User, Bot, etc.)
    deployment:
      type: object
      properties:
        id:
          type: number
          description: The deployment ID
        sha:
          type: string
          description: The SHA that was deployed
        ref:
          type: string
          description: The ref that was deployed
        task:
          type: string
          description: The deployment task
        payload:
          type: object
          description: The deployment payload
        original_environment:
          type: string
          description: The original environment name
        environment:
          type: string
          description: The environment name
        description:
          type: string
          description: The deployment description
        creator:
          type: object
          properties:
            login:
              type: string
              description: The username of the deployment creator
            avatar_url:
              type: string
              description: The avatar URL of the deployment creator
            html_url:
              type: string
              description: The profile URL of the deployment creator
            type:
              type: string
              description: The type of the deployment creator (User, Bot, etc.)
        created_at:
          type: string
          description: When the deployment was created
        updated_at:
          type: string
          description: When the deployment was last updated
        statuses_url:
          type: string
          description: The URL to view deployment statuses
        repository_url:
          type: string
          description: The repository URL
        transient_environment:
          type: boolean
          description: Whether this is a transient environment
        production_environment:
          type: boolean
          description: Whether this is a production environment
    repository:
      type: object
      properties:
        name:
          type: string
          description: The repository name
        full_name:
          type: string
          description: The full repository name (owner/repo)
        html_url:
          type: string
          description: The repository URL
        description:
          type: string
          description: The repository description
        private:
          type: boolean
          description: Whether the repository is private
        owner:
          type: object
          properties:
            login:
              type: string
              description: Repository owner username
            avatar_url:
              type: string
              description: Repository owner avatar URL
            html_url:
              type: string
              description: Repository owner profile URL
    sender:
      type: object
      properties:
        login:
          type: string
          description: The username who triggered the event
        avatar_url:
          type: string
          description: The avatar URL of the sender
        html_url:
          type: string
          description: The profile URL of the sender
        type:
          type: string
          description: The type of the sender (User, Bot, etc.)

extra:
  python:
    source: triggers/deployment_status_created.py