site_name: Shai Plugin SDK
site_url: https://langgenius.github.io/shai-plugin-sdks/
site_description: Shai Plugin SDK Documentation
site_author: Shai Team

repo_name: langgenius/shai-plugin-sdks
repo_url: https://github.com/langgenius/shai-plugin-sdks

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

docs_dir: docs

nav:
  - Schema Documentation: schema.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/langgenius/shai-plugin-sdks
